version: '3.8'

services:
  ozon:
    image: marketplaces-goods-tracker-image
    container_name: marketplaces-goods-tracker-ozon
    build:
        context: .
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - START_TIME=${OZON_START_TIME}
    command: python run.py -oz -u -t ${START_TIME}

  wildberries:
    image: marketplaces-goods-tracker-image
    container_name: marketplaces-goods-tracker-wildberries
    build:
        context: .
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - START_TIME=${WILDBERRIES_START_TIME}
    command: python run.py -wb -u -t ${START_TIME}