services:
  ozon:
    container_name: marketplaces-goods-tracker-ozon
    build:
      context: .
    image: marketplaces-goods-tracker-image
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - TZ
      - START_TIME=${OZON_START_TIME}
    command: python run.py -oz -u -t ${OZON_START_TIME}

  wildberries:
    container_name: marketplaces-goods-tracker-wildberries
    build:
      context: .
    image: marketplaces-goods-tracker-image
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - TZ
      - START_TIME=${WILDBERRIES_START_TIME}
    command: python run.py -wb -u -t ${WILDBERRIES_START_TIME}
